### ISSUE TITLE
Default readPreferences for all transactions

### ISSUE THREAD

**Issue by Raphael-Bahuau** [jamauro/mongo-transactions#4]
According to Mongo doc : https://www.mongodb.com/docs/manual/core/read-preference/#read-preference-and-transactions
Read preference in a transaction should be on primary replicaset, in fact we have set on secondary by default on our app and it won't work unless we specify the option in the transaction.

I think it can be really cool if the `{ readPreference: primary }` option is passed by default.
It avoid passing it on all `Mongo.withTransaction` calls.

You can either pass it on the code of the call, or on the mongo start session code.
Let me know what do you think.

**Comment by jamauro** [comment]
I believe the default is `primary` without needing to specify it 

https://www.mongodb.com/docs/manual/core/transactions/#read-concern-write-concern-read-preference

> If transaction-level and the session-level read preference are unset, the transaction uses the client-level read preference. By default, the client-level read preference is `primary`.

Let me know what you think.

**Comment by jamauro** [comment]
Got it. It seems like a straightforward enough change. Should be able to make it soon.

**Comment by jamauro** [comment]
I just published `v1.2.0` to add this. 🎉
